package ilab.iptv.player.core.data.catalog

import android.content.res.AssetManager
import ilab.iptv.player.core.common.EventCodes
import ilab.iptv.player.core.common.LogCategory
import ilab.iptv.player.core.common.Logger
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.coroutines.withContext
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Loads the bundled P1-2 playlist fixture into the in-memory store exactly once per process.
 *
 * `ensureLoaded()` is idempotent and concurrency-safe: the browse screen can call it from several
 * coroutines (and after a rotation) without parsing the list twice.
 *
 * The asset is a **fixture**, not a source: P1-2 is "load a playlist → channel list" with no network
 * and no database, and `tools/fixtures/README.md` explains why the real 658-channel baseline is not
 * vendored (third-party hosts and token URLs in a public repo). The bundled file is generated by
 * `tools/fixtures/generate-p1-2-baseline.py`: same row count and group mix as the real list,
 * synthetic `.invalid` hosts, plus the `tvg-chno` / `tvg-logo` rows the real list never had so the
 * D12 middle tier and the logo placeholder are exercised on the device.
 *
 * Loading runs on [Dispatchers.IO] because it reads an asset; the parse itself is ~150 KB of text and
 * is measured in the report rather than assumed to be free.
 */
@Singleton
class ChannelCatalogLoader @Inject constructor(
    private val assets: AssetManager,
    private val catalog: ChannelCatalog,
    private val logger: Logger,
) : CatalogBootstrapper {

    private val mutex = Mutex()
    private val stateLock = Any()

    private var loaded = false
    private var lastReport: CatalogLoadReport? = null
    private var lastFailure: Throwable? = null

    /** Parses the bundled fixture into the store on first call; every later call is a no-op. */
    override suspend fun ensureLoaded(): CatalogLoadReport? {
        synchronized(stateLock) {
            if (loaded && lastReport != null) return lastReport
            if (loaded && lastFailure != null) return null
        }
        mutex.withLock {
            synchronized(stateLock) {
                if (loaded && lastReport != null) return lastReport
                if (loaded && lastFailure != null) return null
            }
            return try {
                val report = withContext(Dispatchers.IO) {
                    val text = assets.open(FIXTURE_ASSET).use { it.readBytes().toString(Charsets.UTF_8) }
                    catalog.load(text, FIXTURE_SOURCE_ID)
                }
                logSuccess(report)
                synchronized(stateLock) {
                    loaded = true
                    lastReport = report
                    lastFailure = null
                }
                report
            } catch (e: Exception) {
                logFailure(e)
                synchronized(stateLock) {
                    loaded = true
                    lastFailure = e
                }
                null
            }
        }
    }

    /** The report of the load that happened, or null before the first load / after a failure. */
    fun report(): CatalogLoadReport? = synchronized(stateLock) { lastReport }

    private fun logSuccess(report: CatalogLoadReport) {
        logger.i(
            category = LogCategory.SOURCE,
            code = EventCodes.SRC_PARSE_OK,
            message = "fixture parsed",
            fields = mapOf(
                "provider" to report.sourceId,
                "format" to report.format.label,
                "entries" to report.rawEntries,
                "skipped" to report.skipped,
                "lines" to report.lines,
                "ms" to report.elapsedMs,
            ),
        )
        logger.i(
            category = LogCategory.SOURCE,
            code = EventCodes.SRC_DEDUPE,
            message = "fixture normalized",
            fields = mapOf(
                "raw" to report.streamDedupe.raw,
                "unique" to report.streamDedupe.unique,
                "channels" to report.channels,
                "streams" to report.streams,
                "perSource" to report.streamDedupe.perSource,
            ),
        )
    }

    private fun logFailure(error: Throwable) {
        logger.w(
            category = LogCategory.SOURCE,
            code = EventCodes.SRC_FETCH_FAIL,
            message = "fixture load failed",
            fields = mapOf("provider" to FIXTURE_SOURCE_ID, "asset" to FIXTURE_ASSET, "err" to error.message),
            error = error,
        )
    }

    private companion object {
        const val FIXTURE_ASSET = "playlists/p1-2-baseline.m3u"
        const val FIXTURE_SOURCE_ID = "p1-2-fixture"
    }
}
