package ilab.iptv.spike

import android.content.Context
import org.json.JSONArray
import org.json.JSONObject

/** One sample stream, as generated by tools/make-samples.py into assets/spike/channels.json. */
data class Sample(
    val idx: Int,
    val id: String,
    val name: String,
    val group: String,
    val url: String,
    val vcodec: String?,
    val height: Int?,
    val acodec: String?,
    val source: String,
) {
    fun toJson(): JSONObject = JSONObject()
        .put("idx", idx)
        .put("id", id)
        .put("name", name)
        .put("group", group)
        .put("vcodec_baseline", vcodec ?: JSONObject.NULL)
        .put("height_baseline", height ?: JSONObject.NULL)
        .put("acodec_baseline", acodec ?: JSONObject.NULL)
        .put("source", source)
        .put("url", url)

    companion object {
        fun fromJson(o: JSONObject): Sample = Sample(
            idx = o.optInt("idx", -1),
            id = o.optString("id", ""),
            name = o.optString("name", ""),
            group = o.optString("group", ""),
            url = o.optString("url", ""),
            vcodec = if (o.isNull("vcodec")) null else o.optString("vcodec", null),
            height = if (o.isNull("height")) null else o.optInt("height"),
            acodec = if (o.isNull("acodec")) null else o.optString("acodec", null),
            source = o.optString("source", "unknown"),
        )

        fun list(a: JSONArray?): List<Sample> {
            if (a == null) return emptyList()
            return (0 until a.length()).map { fromJson(a.getJSONObject(it)) }
        }
    }
}

object Samples {

    private var cached: JSONObject? = null

    fun root(context: Context): JSONObject {
        cached?.let { return it }
        val text = context.assets.open("spike/channels.json").bufferedReader().use { it.readText() }
        val json = JSONObject(text)
        cached = json
        return json
    }

    fun s1(context: Context): List<Sample> = Sample.list(root(context).optJSONArray("s1"))

    fun s2(context: Context, key: String): List<Sample> =
        Sample.list(root(context).optJSONObject("s2")?.optJSONArray(key))

    fun s5(context: Context): List<Sample> = Sample.list(root(context).optJSONArray("s5"))
}
